export const Services = [
  {
    "id": 1,
    "category": "Automotive",
    "src": "/service/automotive.jpg",
    "services": [
      {
        "id": 1,
        "name": "Auto spray",
        "src": "/service/auto_spray.jpg",
        "link": "",
      },
      {
        "id": 2,
        "name": "Car ac",
        "src": "/service/car_ac.jpg",
        "link": "",
      },
      {
        "id": 3,
        "name": "Mechanical",
        "src": "/service/mechanic.jpg",
        "link": "",
      },
      {
        "id": 4,
        "name": "panel beater",
        "src": "/service/panel_beater.jpg",
        "link": "",
      },
      {
        "id": 5,
        "name": "re-wire",
        "src": "/service/re-wire.jpg",
        "link": "",
      },
      {
        "id": 6,
        "name": "Towwing",
        "src": "/service/towing.jpg",
        "link": "",
      },
      {
        "id": 7,
        "name": "Vulcanizing",
        "src": "/service/vulcanizers.jpg",
        "link": "",
      },
    ],
  },
  {
    "id": 2,
    "category": "Maintenance",
    "src": "/service/maintenance.jpg",
    "services": [
      {
        "id": 1,
        "name": "AC,Fridge&Cooker",
        "src": "/service/Ac, fridge and cooker.jpg",
        "link": "",
      },
      {
				"id": 2,
				"name": "brick laying",
				"src": "/service/masonry.jpg",
				"link": "",
			},
      {
        "id": 3,
        "name": "Carpentery",
        "src": "/service/carpenters.jpg",
        "link": "",
      },
      {
				"id": 4,
				"name": "Electrical",
				"src": "/service/electrician.jpg",
				"link": "",
			},
      {
        "id": 5,
        "name": "Gardening",
        "src": "/service/gardeners.jpg",
        "link": "",
      },
      {
        "id": 6,
        "name": "Painting",
        "src": "/service/painters.jpg",
        "link": "",
      },
      {
        "id": 7,
        "name": "Phone repair",
        "src": "/service/mobile_repair.jpg",
        "link": "",
      },
      {
        "id": 8,
        "name": "Plumbing",
        "src": "/service/plumbing.jpg",
        "link": "",
      },
      {
				"id": 9,
				"name": "Recycling",
				"src": "/service/rycyclers.jpg",
				"link": "",
			},
      {
				"id": 10,
				"name": "Shoe repair",
				"src": "/service/shoe_repair.jpg",
				"link": "",
			},
      {
        "id": 11,
        "name": "tiling",
        "src": "/service/tiling.jpg",
        "link": "",
      },
      {
        "id": 12,
        "name": "Welding",
        "src": "/service/welding.jpg",
        "link": "",
      },
    ],
  },
  {
    "id": 3,
    "category": "Personal",
    "src": "/service/personal.jpg",
    "services": [
      {
        "id": 1,
        "name": "Architecture",
        "src": "/service/architecture.jpg",
        "link": "",
      },
      {
        "id": 2,
        "name": "Barbing",
        "src": "/service/barbing.jpg",
        "link": "",
      },
      {
        "id": 3,
        "name": "bbq",
        "src": "/service/bbq.jpg",
        "link": "",
      },
      {
        "id": 4,
        "name": "Camera",
        "src": "/service/camera.jpg",
        "link": "",
      },
      {
        "id": 5,
        "name": "Car wash",
        "src": "/service/car_wash.jpg",
        "link": "",
      },
     
      {
        "id": 6,
        "name": "catering",
        "src": "/service/catering.jpg",
        "link": "",
      },
      {
        "id": 7,
        "name": "Delivery",
        "src": "/service/logistic.jpg",
        "link": "",
      },
      {
        "id": 8,
        "name": "Gas delivery",
        "src": "/service/gas.jpg",
        "link": "",
      },
      {
        "id": 9,
        "name": "Islamiya",
        "src": "/service/islamiya.jpg",
        "link": "",
      },
      {
        "id": 10,
        "name": "Home lessons",
        "src": "/service/Home_lesson.jpg",
        "link": "",
      },
      {
        "id": 11,
        "name": "Laundry",
        "src": "/service/laundry.jpg",
        "link": "",
      },
      {
        "id": 12,
        "name": "Medical",
        "src": "/service/phamarcist.jpg",
        "link": "",
      },
      {
        "id": 13,
        "name": "maid",
        "src": "/service/maid.jpg",
        "link": "",
      },
      {
        "id": 14,
        "name": "Manicure",
        "src": "/service/manicure.jpg",
        "link": "",
      },
      
      {
        "id": 15,
        "name": "Real-estate agents",
        "src": "/service/agents.jpg",
        "link": "",
      },
      {
        "id": 16,
        "name": "security",
        "src": "/service/security.jpg",
        "link": "",
      },
      {
        "id": 17,
        "name": "Tailoring",
        "src": "/service/tailor.jpg",
        "link": "",
      },
    ],
  },
];
